//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your email and confirm your account, you must be confirmed before you can log in..
        /// </summary>
        public static string Account_CheckEmailBeforeLogin {
            get {
                return ResourceManager.GetString("Account_CheckEmailBeforeLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have a confirmed email to log on.
        /// </summary>
        public static string Account_ConfirmedEmailBeforeLogon {
            get {
                return ResourceManager.GetString("Account_ConfirmedEmailBeforeLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your LobbyManager® account by clicking &lt;a href=&quot;{0}&quot;&gt;here&lt;/a&gt;{1}.
        /// </summary>
        public static string Account_EmailConfirmAccount {
            get {
                return ResourceManager.GetString("Account_EmailConfirmAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reset your LobbyManager® password by clicking &lt;a href=&quot;{0}&quot;&gt;here&lt;/a&gt;{1}.
        /// </summary>
        public static string Account_EmailResetPassword {
            get {
                return ResourceManager.GetString("Account_EmailResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code.
        /// </summary>
        public static string Account_InvalidCode {
            get {
                return ResourceManager.GetString("Account_InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt.
        /// </summary>
        public static string Account_InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("Account_InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your LobbyManager® account-Resend.
        /// </summary>
        public static string Account_SubjectResendConfirmation {
            get {
                return ResourceManager.GetString("Account_SubjectResendConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyManager® Reset Password.
        /// </summary>
        public static string Account_SubjectResetPassword {
            get {
                return ResourceManager.GetString("Account_SubjectResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your LobbyManager® account.
        /// </summary>
        public static string Account_SubjectSendConfirmation {
            get {
                return ResourceManager.GetString("Account_SubjectSendConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmation token has been resent to your email account.
        /// </summary>
        public static string Account_TokenReSent {
            get {
                return ResourceManager.GetString("Account_TokenReSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string Error_Length {
            get {
                return ResourceManager.GetString("Error_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string Error_PasswordMatch {
            get {
                return ResourceManager.GetString("Error_PasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyManager®.
        /// </summary>
        public static string General_AppName {
            get {
                return ResourceManager.GetString("General_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string General_Code {
            get {
                return ResourceManager.GetString("General_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string General_ConfirmPassword {
            get {
                return ResourceManager.GetString("General_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string General_Email {
            get {
                return ResourceManager.GetString("General_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&amp;nbsp;Best regards,&lt;/p&gt;
        ///&lt;div class=&quot;WordSection1&quot;&gt;
        ///&lt;table class=&quot;MsoTableGrid&quot; style=&quot;border-collapse: collapse; border: none; height: 116px;&quot; border=&quot;0&quot; width=&quot;557&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        ///&lt;tbody&gt;
        ///&lt;tr style=&quot;mso-yfti-irow: 0; mso-yfti-firstrow: yes; mso-yfti-lastrow: yes; height: 87.05pt;&quot;&gt;
        ///&lt;td style=&quot;width: 153.3pt; border: none; border-right: solid windowtext 1.0pt; mso-border-right-alt: solid windowtext .5pt; padding: 0cm 5.4pt 0cm 5.4pt; height: 87.05pt;&quot; valign=&quot;top&quot; width=&quot;204&quot;&gt;&lt;img  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string General_EmailSignature {
            get {
                return ResourceManager.GetString("General_EmailSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string General_Password {
            get {
                return ResourceManager.GetString("General_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M-Robotics Latin America.
        /// </summary>
        public static string General_VendorName {
            get {
                return ResourceManager.GetString("General_VendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your language.
        /// </summary>
        public static string Login_ChooseYourLanguage {
            get {
                return ResourceManager.GetString("Login_ChooseYourLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string Login_ForgotPassword {
            get {
                return ResourceManager.GetString("Login_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login_LoginButton {
            get {
                return ResourceManager.GetString("Login_LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string Login_RegisterNewUser {
            get {
                return ResourceManager.GetString("Login_RegisterNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember this Browser?.
        /// </summary>
        public static string Login_RememberBrowser {
            get {
                return ResourceManager.GetString("Login_RememberBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string Login_RememberMe {
            get {
                return ResourceManager.GetString("Login_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a LobbyManager® account to log in..
        /// </summary>
        public static string Login_UseLocalAccount {
            get {
                return ResourceManager.GetString("Login_UseLocalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainMenu_About {
            get {
                return ResourceManager.GetString("MainMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string MainMenu_Contact {
            get {
                return ResourceManager.GetString("MainMenu_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MainMenu_Home {
            get {
                return ResourceManager.GetString("MainMenu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new account.
        /// </summary>
        public static string Register_CreateNewAccount {
            get {
                return ResourceManager.GetString("Register_CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register_RegisterButton {
            get {
                return ResourceManager.GetString("Register_RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register_Title {
            get {
                return ResourceManager.GetString("Register_Title", resourceCulture);
            }
        }
    }
}
