//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association Form.
        /// </summary>
        public static string Account_AssociationForm {
            get {
                return ResourceManager.GetString("Account_AssociationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your email and confirm your account, you must be confirmed before you can log in..
        /// </summary>
        public static string Account_CheckEmailBeforeLogin {
            get {
                return ResourceManager.GetString("Account_CheckEmailBeforeLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password..
        /// </summary>
        public static string Account_CheckEmailToResetPassword {
            get {
                return ResourceManager.GetString("Account_CheckEmailToResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Click here to Log in.
        /// </summary>
        public static string Account_ClickHereToLogin {
            get {
                return ResourceManager.GetString("Account_ClickHereToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have a confirmed email to log on.
        /// </summary>
        public static string Account_ConfirmedEmailBeforeLogon {
            get {
                return ResourceManager.GetString("Account_ConfirmedEmailBeforeLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        public static string Account_ConfirmEmail {
            get {
                return ResourceManager.GetString("Account_ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your LobbyManager® account by clicking &lt;a href=&quot;{0}&quot;&gt;here&lt;/a&gt;{1}.
        /// </summary>
        public static string Account_EmailConfirmAccount {
            get {
                return ResourceManager.GetString("Account_EmailConfirmAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reset your LobbyManager® password by clicking &lt;a href=&quot;{0}&quot;&gt;here&lt;/a&gt;{1}.
        /// </summary>
        public static string Account_EmailResetPassword {
            get {
                return ResourceManager.GetString("Account_EmailResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your e-mail.
        /// </summary>
        public static string Account_EnterEmail {
            get {
                return ResourceManager.GetString("Account_EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter verification code.
        /// </summary>
        public static string Account_EnterVerificationCode {
            get {
                return ResourceManager.GetString("Account_EnterVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password Confirmation.
        /// </summary>
        public static string Account_ForgotPasswordConfirmation {
            get {
                return ResourceManager.GetString("Account_ForgotPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code.
        /// </summary>
        public static string Account_InvalidCode {
            get {
                return ResourceManager.GetString("Account_InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt.
        /// </summary>
        public static string Account_InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("Account_InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked Out.
        /// </summary>
        public static string Account_LockedOut {
            get {
                return ResourceManager.GetString("Account_LockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been locked out, please try again later..
        /// </summary>
        public static string Account_LockedOutMessage {
            get {
                return ResourceManager.GetString("Account_LockedOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failure.
        /// </summary>
        public static string Account_LoginFailure {
            get {
                return ResourceManager.GetString("Account_LoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful login with service..
        /// </summary>
        public static string Account_LoginFailureMessage {
            get {
                return ResourceManager.GetString("Account_LoginFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string Account_Logoff {
            get {
                return ResourceManager.GetString("Account_Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no external authentication services configured. See &lt;a href=&quot;http://go.microsoft.com/fwlink/?LinkId=403804&quot;&gt;this article&lt;/a&gt; for details on setting up this ASP.NET application to support logging in via external services..
        /// </summary>
        public static string Account_NoAuthenticationServicesMessage {
            get {
                return ResourceManager.GetString("Account_NoAuthenticationServicesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Account_Register {
            get {
                return ResourceManager.GetString("Account_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string Account_ResetPassword {
            get {
                return ResourceManager.GetString("Account_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Account_ResetPasswordButton {
            get {
                return ResourceManager.GetString("Account_ResetPasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password confirmation.
        /// </summary>
        public static string Account_ResetPasswordConfirmation {
            get {
                return ResourceManager.GetString("Account_ResetPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password.
        /// </summary>
        public static string Account_ResetYourPassword {
            get {
                return ResourceManager.GetString("Account_ResetYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Two-Factor Authentication Provider:.
        /// </summary>
        public static string Account_SelectTwoFactorAuthProvider {
            get {
                return ResourceManager.GetString("Account_SelectTwoFactorAuthProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Account_Send {
            get {
                return ResourceManager.GetString("Account_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Link.
        /// </summary>
        public static string Account_SendEmailLink {
            get {
                return ResourceManager.GetString("Account_SendEmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send verification code.
        /// </summary>
        public static string Account_SendVerificationCode {
            get {
                return ResourceManager.GetString("Account_SendVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your LobbyManager® account-Resend.
        /// </summary>
        public static string Account_SubjectResendConfirmation {
            get {
                return ResourceManager.GetString("Account_SubjectResendConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyManager® Reset Password.
        /// </summary>
        public static string Account_SubjectResetPassword {
            get {
                return ResourceManager.GetString("Account_SubjectResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your LobbyManager® account.
        /// </summary>
        public static string Account_SubjectSendConfirmation {
            get {
                return ResourceManager.GetString("Account_SubjectSendConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully authenticated with &lt;strong&gt;{0}&lt;/strong&gt;. Please enter a user name for this site below and click the &apos;{1}&apos; button to finish logging in..
        /// </summary>
        public static string Account_SuccessfullAuthMessage {
            get {
                return ResourceManager.GetString("Account_SuccessfullAuthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your email.
        /// </summary>
        public static string Account_ThankYouForConfirmEmail {
            get {
                return ResourceManager.GetString("Account_ThankYouForConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmation token has been resent to your email account.
        /// </summary>
        public static string Account_TokenReSent {
            get {
                return ResourceManager.GetString("Account_TokenReSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use another service to log in..
        /// </summary>
        public static string Account_UseAnotherServiceLogin {
            get {
                return ResourceManager.GetString("Account_UseAnotherServiceLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string Account_Verify {
            get {
                return ResourceManager.GetString("Account_Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset.
        /// </summary>
        public static string Account_YourPasswordHasBeenReset {
            get {
                return ResourceManager.GetString("Account_YourPasswordHasBeenReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string Error_Length {
            get {
                return ResourceManager.GetString("Error_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string Error_PasswordMatch {
            get {
                return ResourceManager.GetString("Error_PasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyManager®.
        /// </summary>
        public static string General_AppName {
            get {
                return ResourceManager.GetString("General_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string General_Change {
            get {
                return ResourceManager.GetString("General_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string General_Code {
            get {
                return ResourceManager.GetString("General_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string General_ConfirmPassword {
            get {
                return ResourceManager.GetString("General_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string General_Create {
            get {
                return ResourceManager.GetString("General_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string General_Disable {
            get {
                return ResourceManager.GetString("General_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string General_Email {
            get {
                return ResourceManager.GetString("General_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&amp;nbsp;Best regards,&lt;/p&gt;
        ///&lt;div class=&quot;WordSection1&quot;&gt;
        ///&lt;table class=&quot;MsoTableGrid&quot; style=&quot;border-collapse: collapse; border: none; height: 116px;&quot; border=&quot;0&quot; width=&quot;557&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        ///&lt;tbody&gt;
        ///&lt;tr style=&quot;mso-yfti-irow: 0; mso-yfti-firstrow: yes; mso-yfti-lastrow: yes; height: 87.05pt;&quot;&gt;
        ///&lt;td style=&quot;width: 153.3pt; border: none; border-right: solid windowtext 1.0pt; mso-border-right-alt: solid windowtext .5pt; padding: 0cm 5.4pt 0cm 5.4pt; height: 87.05pt;&quot; valign=&quot;top&quot; width=&quot;204&quot;&gt;&lt;img  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string General_EmailSignature {
            get {
                return ResourceManager.GetString("General_EmailSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string General_Enable {
            get {
                return ResourceManager.GetString("General_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string General_ErrorMessage {
            get {
                return ResourceManager.GetString("General_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string General_ErrorTitle {
            get {
                return ResourceManager.GetString("General_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info..
        /// </summary>
        public static string General_Info {
            get {
                return ResourceManager.GetString("General_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        public static string General_Lastname {
            get {
                return ResourceManager.GetString("General_Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string General_Manage {
            get {
                return ResourceManager.GetString("General_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string General_Name {
            get {
                return ResourceManager.GetString("General_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string General_None {
            get {
                return ResourceManager.GetString("General_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string General_Password {
            get {
                return ResourceManager.GetString("General_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Image.
        /// </summary>
        public static string General_ProfileImage {
            get {
                return ResourceManager.GetString("General_ProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string General_Remove {
            get {
                return ResourceManager.GetString("General_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string General_Submit {
            get {
                return ResourceManager.GetString("General_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M-Robotics Latin America.
        /// </summary>
        public static string General_VendorName {
            get {
                return ResourceManager.GetString("General_VendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string General_WelcomeLabel {
            get {
                return ResourceManager.GetString("General_WelcomeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your language.
        /// </summary>
        public static string Login_ChooseYourLanguage {
            get {
                return ResourceManager.GetString("Login_ChooseYourLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string Login_ForgotPassword {
            get {
                return ResourceManager.GetString("Login_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login_LoginButton {
            get {
                return ResourceManager.GetString("Login_LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string Login_RegisterNewUser {
            get {
                return ResourceManager.GetString("Login_RegisterNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember this Browser?.
        /// </summary>
        public static string Login_RememberBrowser {
            get {
                return ResourceManager.GetString("Login_RememberBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string Login_RememberMe {
            get {
                return ResourceManager.GetString("Login_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a LobbyManager® account to log in..
        /// </summary>
        public static string Login_UseLocalAccount {
            get {
                return ResourceManager.GetString("Login_UseLocalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainMenu_About {
            get {
                return ResourceManager.GetString("MainMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string MainMenu_Contact {
            get {
                return ResourceManager.GetString("MainMenu_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MainMenu_Home {
            get {
                return ResourceManager.GetString("MainMenu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a phone number.
        /// </summary>
        public static string Manage_AddPhoneNumber {
            get {
                return ResourceManager.GetString("Manage_AddPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Manage_ChangePassword {
            get {
                return ResourceManager.GetString("Manage_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string Manage_ChangePasswordButton {
            get {
                return ResourceManager.GetString("Manage_ChangePasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Form.
        /// </summary>
        public static string Manage_ChangePasswordForm {
            get {
                return ResourceManager.GetString("Manage_ChangePasswordForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your account settings.
        /// </summary>
        public static string Manage_ChangeYourAccountSettings {
            get {
                return ResourceManager.GetString("Manage_ChangeYourAccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        public static string Manage_ChangeYourPassword {
            get {
                return ResourceManager.GetString("Manage_ChangeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string Manage_ConfirmNewPassword {
            get {
                return ResourceManager.GetString("Manage_ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Local Login.
        /// </summary>
        public static string Manage_CreateLocalLogin {
            get {
                return ResourceManager.GetString("Manage_CreateLocalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Password.
        /// </summary>
        public static string Manage_CreatePassword {
            get {
                return ResourceManager.GetString("Manage_CreatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string Manage_CurrentPassword {
            get {
                return ResourceManager.GetString("Manage_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Code.
        /// </summary>
        public static string Manage_EmailCode {
            get {
                return ResourceManager.GetString("Manage_EmailCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter verification code.
        /// </summary>
        public static string Manage_EnterVerificationCode {
            get {
                return ResourceManager.GetString("Manage_EnterVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external login was removed..
        /// </summary>
        public static string Manage_ExternalLoginRemoved {
            get {
                return ResourceManager.GetString("Manage_ExternalLoginRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Logins.
        /// </summary>
        public static string Manage_ExternalLogins {
            get {
                return ResourceManager.GetString("Manage_ExternalLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to verify phone.
        /// </summary>
        public static string Manage_FailedToVerifyPhone {
            get {
                return ResourceManager.GetString("Manage_FailedToVerifyPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password.
        /// </summary>
        public static string Manage_IncorrectPassword {
            get {
                return ResourceManager.GetString("Manage_IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in using your {0} account.
        /// </summary>
        public static string Manage_LoginUsingAuthAccount {
            get {
                return ResourceManager.GetString("Manage_LoginUsingAuthAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your external logins.
        /// </summary>
        public static string Manage_ManageExternalLogins {
            get {
                return ResourceManager.GetString("Manage_ManageExternalLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string Manage_NewPassword {
            get {
                return ResourceManager.GetString("Manage_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no external authentication services configured..
        /// </summary>
        public static string Manage_NoExternalAuthServicesConfigured {
            get {
                return ResourceManager.GetString("Manage_NoExternalAuthServicesConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have a local username/password for this site. Add a local account so you can log in without an external login..
        /// </summary>
        public static string Manage_NoLocalAccountMessage {
            get {
                return ResourceManager.GetString("Manage_NoLocalAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Code.
        /// </summary>
        public static string Manage_PhoneCode {
            get {
                return ResourceManager.GetString("Manage_PhoneCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Manage_PhoneNumber {
            get {
                return ResourceManager.GetString("Manage_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number was added..
        /// </summary>
        public static string Manage_PhoneNumberAdded {
            get {
                return ResourceManager.GetString("Manage_PhoneNumberAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number was removed..
        /// </summary>
        public static string Manage_PhoneNumberRemoved {
            get {
                return ResourceManager.GetString("Manage_PhoneNumberRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Logins.
        /// </summary>
        public static string Manage_RegisteredLogins {
            get {
                return ResourceManager.GetString("Manage_RegisteredLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this {0} login from your account.
        /// </summary>
        public static string Manage_RemoveAuthProviderFromAccount {
            get {
                return ResourceManager.GetString("Manage_RemoveAuthProviderFromAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Code - LobbyManager®.
        /// </summary>
        public static string Manage_SecurityCodeEmailSubject {
            get {
                return ResourceManager.GetString("Manage_SecurityCodeEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set password.
        /// </summary>
        public static string Manage_SetPassword {
            get {
                return ResourceManager.GetString("Manage_SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-Factor Authentication.
        /// </summary>
        public static string Manage_TwoFactorAuth {
            get {
                return ResourceManager.GetString("Manage_TwoFactorAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your two-factor authentication provider has been set..
        /// </summary>
        public static string Manage_TwoFactorProviderSet {
            get {
                return ResourceManager.GetString("Manage_TwoFactorProviderSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Phone Number.
        /// </summary>
        public static string Manage_VerifyPhoneNumber {
            get {
                return ResourceManager.GetString("Manage_VerifyPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your security code is: {0}.
        /// </summary>
        public static string Manage_YourEmailSecurityCodeIs {
            get {
                return ResourceManager.GetString("Manage_YourEmailSecurityCodeIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed..
        /// </summary>
        public static string Manage_YourPasswordHasBeenChanged {
            get {
                return ResourceManager.GetString("Manage_YourPasswordHasBeenChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been set..
        /// </summary>
        public static string Manage_YourPasswordHasBeenSet {
            get {
                return ResourceManager.GetString("Manage_YourPasswordHasBeenSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your security code is: {0}.
        /// </summary>
        public static string Manage_YourPhoneSecurityCodeIs {
            get {
                return ResourceManager.GetString("Manage_YourPhoneSecurityCodeIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new account.
        /// </summary>
        public static string Register_CreateNewAccount {
            get {
                return ResourceManager.GetString("Register_CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register_RegisterButton {
            get {
                return ResourceManager.GetString("Register_RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register_Title {
            get {
                return ResourceManager.GetString("Register_Title", resourceCulture);
            }
        }
    }
}
